export enum NotificationCode {
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_INPUT = 'MISSING_INPUT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_REQUEST = 'INVALID_REQUEST',
  
  SETUP_INVALID_LANGUAGE = 'SETUP_INVALID_LANGUAGE',
  SETUP_DATABASE_PASSWORD_TOO_SHORT = 'SETUP_DATABASE_PASSWORD_TOO_SHORT',
  SETUP_ADMIN_USERNAME_TOO_SHORT = 'SETUP_ADMIN_USERNAME_TOO_SHORT',
  SETUP_ADMIN_PASSWORD_TOO_SHORT = 'SETUP_ADMIN_PASSWORD_TOO_SHORT',
  
  EMLAT_UPDATED = 'EMLAT_UPDATED',

  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_INVALID_SESSION = 'AUTH_INVALID_SESSION',
  
  LOGIN_BAD_CREDENTIALS = 'LOGIN_BAD_CREDENTIALS',
  LOGIN_USERNAME_TOO_SHORT = 'LOGIN_USERNAME_MIN_LENGTH',
  LOGIN_USERNAME_TOO_LONG = 'LOGIN_USERNAME_MAX_LENGTH',

  REGISTER_USERNAME_TOO_SHORT = 'REGISTER_USERNAME_MIN_LENGTH',
  REGISTER_USERNAME_TOO_LONG = 'REGISTER_USERNAME_MAX_LENGTH',
  REGISTER_PASSWORD_TOO_SHORT = 'REGISTER_PASSWORD_MIN_LENGTH',
  REGISTER_PIN_INVALID = 'REGISTER_PIN_INVALID',
  REGISTER_USERNAME_EXISTS = 'REGISTER_USERNAME_EXISTS',

  DATABASE_ERROR = 'DATABASE_ERROR',
  FILE_SYSTEM_ERROR = 'FILE_SYSTEM_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  EXTERNAL_API_ERROR = 'EXTERNAL_API_ERROR',
}
