export enum NotificationMessage {
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_INPUT = 'MISSING_INPUT',
  DATABASE_ERROR = 'DATABASE_ERROR',
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  INVALID_REQUEST = 'INVALID_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  
  
  SETUP_LANGUAGE_LENGTH = 'LANGUAGE_LENGTH',
  SETUP_DB_PASSWORD_MIN_LENGTH = 'DB_PASSWORD_MIN_LENGTH',
  SETUP_ADMIN_USERNAME_MIN_LENGTH = 'ADMIN_USERNAME_MIN_LENGTH',
  SETUP_ADMIN_PASSWORD_MIN_LENGTH = 'ADMIN_PASSWORD_MIN_LENGTH',

  LOGIN_BAD_CREDENTIALS = 'BAD_CREDENTIALS'
}

