# Devloppement configuration

name: eml_admintool

services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../api:/usr/src/app/api
      - ../client:/usr/src/app/client
      - ../shared:/usr/src/app/shared
    ports:
      - '3000:3000'
      - '5173:5173'
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'eml'
      MYSQL_DATABASE: 'eml_admintool'
    volumes:
      - mysql-data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql

volumes:
  mysql-data:
