# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#              PRODUCTION CONFIGURATION               #
#                                                     #
# This file is used to setup the application in a     #
# production environment.                             #
#                                                     #
# You should only use this once, to deploy the        #
# application to a server. Please DO NOT use this     #
# file to restart the application: if the application #
# has been updated, using this file may downgrade     #
# the application to an older version.                #
# You can use `docker start <container_name>` to      #
# start or restart the application.                   #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #

name: eml-admintool

networks:
  network:

services:
  web:
    image: ghcr.io/electron-minecraft-launcher/eml-admintool-v2:latest
    restart: unless-stopped
    networks:
      - network
    environment:
      NODE_ENV: 'production'
    volumes:
      - files:/app/files
      - env:/app/env
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - '8080:3000'
    depends_on:
      - dbs
  dbs:
    image: postgres:latest
    restart: unless-stopped
    networks:
      - network
    environment:
      POSTGRES_USER: eml
      POSTGRES_PASSWORD: eml
      POSTGRES_DB: eml_admintool
    volumes:
      - db-data:/var/lib/postgresql/data
  wtw:
    image: ghcr.io/electron-minecraft-launcher/watchtower-for-emlat:latest
    networks:
      - network
    volumes:
      - env:/config:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - com.eml.admintool.watchtower=prod
    depends_on:
      - web

volumes:
  db-data:
  files:
  env:
