FROM node:20

WORKDIR /app

ENV CHOKIDAR_USEPOLLING=true

RUN wget -qO- https://download.docker.com/linux/static/stable/x86_64/docker-20.10.8.tgz | tar -xz && \
  mv docker/docker /usr/local/bin/ && \
  rm -rf docker

RUN wget -O /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/v2.33.0/docker-compose-linux-x86_64 && \
  chmod +x /usr/local/bin/docker-compose

COPY package*.json ./

RUN mkdir api client shared
COPY api/package*.json ./api
COPY client/package*.json ./client
COPY shared/package*.json ./shared

RUN npm i
RUN npm i --workspace=api
RUN npm i --workspace=client
RUN npm i --workspace=shared

COPY api ./api
COPY client ./client
COPY shared ./shared

EXPOSE 3000 5173

CMD ["npm", "run", "dev"]
