# Devloppement configuration

name: eml_admintool

services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../api:/usr/src/app/api
      - ../client:/usr/src/app/client
      - ../shared:/usr/src/app/shared
      - files:/usr/src/app/files
    ports:
      - '3000:3000'
      - '5173:5173'
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'eml_admintool'
      MYSQL_USER: 'eml'
      MYSQL_PASSWORD: 'eml'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql

volumes:
  mysql-data:
  files:
