# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#              PRODUCTION CONFIGURATION               #
#                                                     #
# This file is used to run the application in a       #
# production environment.                             #
# Please use it with an existing Docker image. You    #
# can download an image from GitHub or build your     #
# own image using the Dockerfile.build file.          #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #

name: eml_admintool

services:
  web:
    image: eml-admintool:2.0.0-alpha.13
    environment:
      NODE_ENV: 'production'
      PORT: 4000
    volumes:
      - files:/app/files
      - env:/app/api/env
      - loader:/app/loader
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'eml_admintool'
      MYSQL_USER: 'eml'
      MYSQL_PASSWORD: 'eml'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  files:
  loader:
  env:
