FROM node:24-alpine

WORKDIR /app

ENV CHOKIDAR_USEPOLLING=true

RUN apk add --no-cache docker-cli

COPY package.json ./
COPY docker/entrypoint.dev.sh ./entrypoint.dev.sh

RUN chmod +x /app/entrypoint.dev.sh
RUN npm i --ignore-scripts

EXPOSE 5173

ENTRYPOINT ["/app/entrypoint.dev.sh"]
# wait command
# CMD ["tail", "-f", "/dev/null"]
