services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../api:/app/api
      - ../client:/app/client
      - ../shared:/app/shared
    ports:
      - '3000:3000'
      - '5173:5173'
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: 'eml_admintool'
      MYSQL_USER: 'eml'
      MYSQL_PASSWORD: 'eml'
    volumes:
      - mysql-data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql

volumes:
  mysql-data:
