# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                BUIDLD CONFIGURATION                 #
#                                                     #
# This file is used to build the application.         #
# You wan use it to build your application locally or #
# to create your own Docker image.                    #
#                                                     #
# If you want to run a production environment, you    #
# should use the docker-compose.prod.yml file with    #
# an existing Docker image.                           #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #

name: eml_admintool

services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.prod
    environment:
      NODE_ENV: 'production'
      PORT: 4000
    volumes:
      - files:/app/files
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'eml_admintool'
      MYSQL_USER: 'eml'
      MYSQL_PASSWORD: 'eml'
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
  files:
