# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#              PRODUCTION CONFIGURATION               #
#                                                     #
# This file is used to setup the application in a     #
# production environment.                             #
#                                                     #
# You should only use this once, to deploy the        #
# application to a server. Please DO NOT use this     #
# file to restart the application: if the application #
# has been updated, using this file may downgrade     #
# the application to an older version.                #
# You can use `docker start <container_name>` to      #
# start or restart the application.                   #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #

name: eml_admintool

services:
  web:
    image: eml-admintool:2.0.0-beta.2
    environment:
      NODE_ENV: 'production'
    volumes:
      - files:/app/files
      - env/.env:/app/.env
      - loader:/app/loader
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: eml
      POSTGRES_PASSWORD: eml
      POSTGRES_DB: eml_admintool
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db-data:
  files:
  loader:
  env:
