FROM node:24-alpine

WORKDIR /app

ENV CHOKIDAR_USEPOLLING=true

RUN wget -qO- https://download.docker.com/linux/assets/stable/x86_64/docker-28.3.0.tgz | tar -xz && \
  mv docker/docker /usr/local/bin/ && \
  rm -rf docker

RUN wget -O /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/v2.38.1/docker-compose-linux-x86_64 && \
  chmod +x /usr/local/bin/docker-compose

COPY package.json ./

RUN npm i

EXPOSE 5173

CMD ["npm", "run", "dev"]
# wait command
# CMD ["tail", "-f", "/dev/null"]
