name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-beta.*'
      - 'v*.*.*-alpha.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify branch is main
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          BRANCHES=$(git branch -r --contains tags/$TAG)
          if [[ ! "$BRANCHES" == *"origin/main"* ]]; then
            echo "Tag $TAG is not on the main branch. Stopping workflow."
            exit 1
          fi

      - name: Build Docker image
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          IMAGE_TAG=${TAG#v}
          docker build -t eml-admintool:$IMAGE_TAG -f docker/Dockerfile.build .
      
      - name: Save Docker image
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          IMAGE_TAG=${TAG#v}
          docker save eml-admintool:$IMAGE_TAG > eml-admintool-$IMAGE_TAG.tar
          echo "TAR_FILE=$TAR_FILE" >> $GITHUB_ENV
      
      - name: Create tarball
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          IMAGE_TAG=${TAG#v}
          TAR_FILE=eml-admintool-$IMAGE_TAG.tar.gz
          tar -czf $TAR_FILE eml-admintool-$IMAGE_TAG.tar docker/docker-compose.prod.yml
          echo "TAR_FILE=$TAR_FILE" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
      
      - name: Upload tarball
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.TAR_FILE }}
          asset_name: ${{ env.TAR_FILE }}
          asset_content_type: application/gzip
        