name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-beta.*'
      - 'v*.*.*-alpha.*'

jobs:
  build:
    name: Build, publish Release and Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify branch is main
        run: |
          if ! git branch -r --contains ${{ github.ref_name }} | grep -q "origin/main"; then
            echo "Error: Tag ${{ github.ref_name }} is not on the main branch."
            exit 1
          fi
          echo "✅ Tag is on the main branch."

      - name: Verify changelog file exists
        run: |
          CHANGELOG_FILE=".github/changelogs/${{ github.ref_name }}.md"
          if [ ! -f "$CHANGELOG_FILE" ]; then
            echo "Error: Changelog file $CHANGELOG_FILE does not exist."
            exit 1
          fi
          echo "✅ Changelog file found."

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
      
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.build
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: EML AdminTool ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          body_path: .github/changelogs/${{ github.ref_name }}.md
          files: docker/docker-compose.prod.yml
